import { Deal, SubscriptionPlan, SubscriptionTier } from './types';

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    tier: SubscriptionTier.FREE,
    name: 'Free',
    name_tr: 'Ücretsiz',
    price: 0,
    price_tr: 0,
    redemptionsPerMonth: 3,
    billingPeriod: 'yearly',
    features: [
      'Access to select local deals',
      'Personalized deal alerts',
      'Basic support'
    ],
    features_tr: [
      'Seçili yerel fırsatlara erişim',
      'Kişiselleştirilmiş fırsat uyarıları',
      'Temel destek'
    ],
  },
  {
    tier: SubscriptionTier.BASIC,
    name: 'Basic',
    name_tr: 'Temel',
    price: 119.88, // $9.99 × 12
    price_tr: 4199.88, // 349.99 TL × 12
    redemptionsPerMonth: 10,
    billingPeriod: 'yearly',
    features: ['Access to local dining deals', 'Weekly newsletter', 'Standard support'],
    features_tr: ['Yerel yemek fırsatlarına erişim', 'Haftalık bülten', 'Standart destek'],
  },
  {
    tier: SubscriptionTier.PREMIUM,
    name: 'Premium',
    name_tr: 'Premium',
    price: 239.88, // $19.99 × 12
    price_tr: 8399.88, // 699.99 TL × 12
    redemptionsPerMonth: 30,
    billingPeriod: 'yearly',
    features: ['All Basic features', 'Exclusive travel deals', 'Early access to new deals', 'Priority support'],
    features_tr: ['Tüm Temel özellikler', 'Özel seyahat fırsatları', 'Yeni fırsatlara erken erişim', 'Öncelikli destek'],
  },
  {
    tier: SubscriptionTier.VIP,
    name: 'VIP',
    name_tr: 'VIP',
    price: 599.88, // $49.99 × 12
    price_tr: 20399.88, // 1699.99 TL × 12
    redemptionsPerMonth: Infinity,
    billingPeriod: 'yearly',
    features: ['All Premium features', 'AI-powered trip planning', 'Concierge service', 'Partner event invitations'],
    features_tr: [
      'Tüm Premium özellikler',
      'Yapay zeka destekli gezi planlama',
      'Konsiyerj hizmeti',
      'Partner etkinlik davetiyeleri'
    ],
  },
];

const getExpiryDate = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const MOCK_DEALS: Deal[] = [
  {
    id: '1',
    title: 'Exclusive Dining Experience',
    title_tr: 'Özel Akşam Yemeği Deneyimi',
    description: 'Enjoy a curated dining experience at a top-rated restaurant in Istanbul, offering a special menu for our subscribers.',
    description_tr: 'Abonelerimize özel bir menü sunan, İstanbul\'un en prestijli restoranlarından birinde özenle hazırlanmış bir akşam yemeği deneyiminin keyfini çıkarın.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80',
    category: 'Dining',
    category_tr: 'Yemek',
    originalPrice: 120,
    discountedPrice: 80,
    requiredTier: SubscriptionTier.PREMIUM,
    isExternal: false,
    vendor: 'WanderWise Exclusives',
    expiresAt: getExpiryDate(2),
    rating: 4.8,
    ratingCount: 125,
    usageLimit: '1 per user',
    usageLimit_tr: 'Kullanıcı başına 1',
    validity: 'Valid until December 31, 2024',
    validity_tr: '31 Aralık 2024 tarihine kadar geçerli',
    termsUrl: '#',
    redemptionCode: 'WW-DINING-XYZ',
  },
  {
    id: '2',
    title: 'Relaxing Spa Retreat',
    title_tr: 'Rahatlatıcı Spa Kaçamağı',
    description: 'Indulge in a rejuvenating spa day with massage and facial.',
    description_tr: 'Masaj ve yüz bakımı ile canlandırıcı bir spa gününün keyfini çıkarın.',
    imageUrl: 'https://images.unsplash.com/photo-1544161515-cfd636ee4844?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80',
    category: 'Wellness',
    category_tr: 'Sağlık',
    originalPrice: 150,
    discountedPrice: 100,
    requiredTier: SubscriptionTier.PREMIUM,
    isExternal: false,
    vendor: 'WanderWise Exclusives',
    expiresAt: getExpiryDate(5),
    rating: 4.5,
    ratingCount: 88,
    usageLimit: '1 per booking',
    usageLimit_tr: 'Rezervasyon başına 1',
    validity: 'Valid for 3 months from purchase',
    validity_tr: 'Satın alındıktan sonra 3 ay geçerli',
    termsUrl: '#',
    redemptionCode: 'WW-SPA-ABC',
  },
  {
    id: '3',
    title: 'Weekend Getaway to Cappadocia',
    title_tr: 'Kapadokya\'ya Hafta Sonu Kaçamağı',
    description: 'Experience the magical landscapes with a hot air balloon ride.',
    description_tr: 'Sıcak hava balonu gezisi ile büyülü manzaraları deneyimleyin.',
    imageUrl: 'https://images.unsplash.com/photo-1593436528333-a2453853846c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80',
    category: 'Travel',
    category_tr: 'Seyahat',
    originalPrice: 250,
    discountedPrice: 200,
    requiredTier: SubscriptionTier.VIP,
    isExternal: false,
    vendor: 'WanderWise Exclusives',
    expiresAt: getExpiryDate(10),
    rating: 4.9,
    ratingCount: 210,
    usageLimit: '2 people per deal',
    usageLimit_tr: 'Fırsat başına 2 kişi',
    validity: 'Only valid on weekends',
    validity_tr: 'Sadece hafta sonları geçerli',
    termsUrl: '#',
    redemptionCode: 'CAPP-VIP-2024',
  },
  {
    id: '4',
    title: 'Antalya All-Inclusive Resort',
    title_tr: 'Antalya Her Şey Dahil Tatil Köyü',
    description: '7 nights at a family-friendly all-inclusive resort on the Mediterranean coast.',
    description_tr: 'Akdeniz kıyısında aile dostu bir tatil köyünde 7 gece her şey dahil konaklama.',
    imageUrl: 'https://picsum.photos/seed/resort/400/300',
    category: 'Travel',
    category_tr: 'Seyahat',
    originalPrice: 1200,
    discountedPrice: 950,
    requiredTier: SubscriptionTier.PREMIUM,
    isExternal: true,
    vendor: 'EnjoyMyDeals',
    expiresAt: getExpiryDate(15),
    rating: 3.8,
    ratingCount: 45,
    usageLimit: 'Family of 4',
    usageLimit_tr: '4 kişilik aile',
    validity: 'Valid for summer season',
    validity_tr: 'Yaz sezonunda geçerli',
    termsUrl: '#',
    redemptionCode: 'ANTALYA-SUN-950',
  },
  {
    id: '5',
    title: 'Traditional Turkish Dinner',
    title_tr: 'Geleneksel Türk Akşam Yemeği',
    description: '2-for-1 deal at a top-rated traditional Turkish restaurant in Sultanahmet.',
    description_tr: 'Sultanahmet\'teki en iyi geleneksel Türk restoranlarından birinde 2 kişilik fırsat.',
    imageUrl: 'https://picsum.photos/seed/dinner/400/300',
    category: 'Dining',
    category_tr: 'Yemek',
    originalPrice: 100,
    discountedPrice: 50,
    requiredTier: SubscriptionTier.FREE,
    isExternal: false,
    vendor: 'WanderWise Exclusives',
    expiresAt: getExpiryDate(3),
    rating: 4.2,
    ratingCount: 67,
    usageLimit: '2 per table',
    usageLimit_tr: 'Masa başına 2',
    validity: 'Valid on weekdays',
    validity_tr: 'Hafta içi geçerli',
    termsUrl: '#',
    redemptionCode: 'SULTAN-2FOR1',
  },
  {
    id: '6',
    title: 'Istanbul Airport Lounge Access',
    title_tr: 'İstanbul Havalimanı Lounge Erişimi',
    description: 'Get exclusive access to the premium lounge at Istanbul Airport.',
    description_tr: 'İstanbul Havalimanı\'ndaki premium lounge\'a özel erişim elde edin.',
    imageUrl: 'https://picsum.photos/seed/lounge/400/300',
    category: 'Travel',
    category_tr: 'Seyahat',
    originalPrice: 75,
    discountedPrice: 50,
    requiredTier: SubscriptionTier.BASIC,
    isExternal: true,
    vendor: 'EnjoyMyDeals',
    expiresAt: getExpiryDate(30),
    rating: 0,
    ratingCount: 0,
    usageLimit: '1 per person per flight',
    usageLimit_tr: 'Uçuş başına kişi başı 1',
    validity: 'Valid for 1 year',
    validity_tr: '1 yıl geçerli',
    termsUrl: '#',
    redemptionCode: 'IST-LOUNGE-50',
  },
];
