


// FIX: Removed a circular import of 'translations' from '../localization'.
// This file is the source of the 'translations' object and should not be importing it.
export const translations = {
  en: {
    // Header
    navHome: 'Home',
    navSubscriptions: 'Subscriptions',
    login: 'Login',
    logout: 'Logout',
    bottomNavHome: 'Home',
    bottomNavTravel: 'Travel',
    bottomNavWallet: 'Wallet',
    bottomNavProfile: 'Profile',
    bottomNavAdmin: 'Admin',
    bottomNavWishlist: 'Wishlist',
    collectionHubTitle: 'Collection',
    collectionHubSubtitle: 'Your personal hub for active deals and wishlist',
    walletTabActive: 'Active',
    walletTabHistory: 'History',
    walletUseNow: 'Use Now',
    walletExpiresToday: 'Expires Today',
    walletExpiresSoon: 'Expires Soon',
    flightsMovedTitle: 'Flights are now in Travel Hub',
    flightsMovedSubtitle: 'We have moved all travel-related features to our new dedicated section.',
    goToTravelHub: 'Visit Travel Hub',
    onboardingWelcome: 'Welcome to Tripzy! ✨',
    onboardingTravelStyleQuestion: "What's your ideal travel style?",
    onboardingBudgetQuestion: "What's your budget preference?",
    onboardingBudgetSubtitle: "We'll show you the best deals for your style",
    onboardingBenefit1Title: 'Discover Exclusive Deals',
    onboardingBenefit1Desc: 'Access thousands of premium travel discounts.',
    onboardingBenefit2Title: 'Easy Redemption',
    onboardingBenefit2Desc: 'Get your coupon code and redeem instantly.',
    onboardingBenefit3Title: 'Membership Perks',
    onboardingBenefit3Desc: 'Upgrade to unlock even more savings.',
    skip: 'Skip',
    next: 'Next',
    back: 'Back',
    getStarted: 'Get Started',
    travelStyleBeach: 'Beach & Relaxation',
    travelStyleMountain: 'Mountain & Nature',
    travelStyleCity: 'City & Culture',
    travelStyleAdventure: 'Adventure & Sports',
    onboardingQuote: 'Travel is the only thing you buy that makes you richer.',
    onboardingTravelStyleSubtitle: 'What excites you the most? Select one or more.',
    welcome: 'Welcome',
    searchPlaceholder: 'Search for deals',
    // Personalized Greetings
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    greetingNight: 'Good night',
    greetingSubtitleMorning: "Start your day with amazing deals! ☀️",
    greetingSubtitleAfternoon: "Here are today's best picks for you 🌤️",
    greetingSubtitleEvening: "Wind down with these exclusive offers 🌙",
    greetingSubtitleNight: "Late night deals just for you 🌟",
    // Home Page
    heroTitle: 'Exclusive Global Travel Deals & VIP Experiences',
    heroSubtitle: 'Unlock up to 70% off on luxury hotels, flights, and dining experiences worldwide.',
    homeTitle: 'Tripzy - Global Travel Discounts & Deals',
    homeDescription: 'Discover exclusive discounts on hotels, flights, and restaurants worldwide with Tripzy. Best travel deals at your fingertips.',
    featuredDeals: 'Featured Deals',
    noResults: 'No deals found matching your search.',
    recentSearches: 'Recent Searches',
    clear: 'Clear',
    noRecentSearches: 'No recent searches.',
    filterByRating: 'Filter by Rating',
    allRatings: 'All',
    // Categories
    categoryAll: 'All',
    categoryFlights: 'Flights',
    categoryDining: 'Dining',
    categoryWellness: 'Wellness',
    categoryTravel: 'Travel',
    faqTitle: 'Tripzy - Help Center & FAQ',
    faqDescription: 'Find answers to all your questions about Tripzy travel deals and subscriptions.',
    flightsPageTitle: 'Flight Deals & Discounts - Tripzy',
    flightsPageDescription: 'Discover the best flight deals across the globe. Save on every flight with Tripzy.',
    travelPageTitle: 'Exclusive Travel & Hotel Deals - Tripzy',
    travelPageDescription: 'Unlock premium discounts on hotels, resorts, and vacation packages worldwide.',
    findFlightsTitle: 'FLIGHTS DISCOVERY',
    loadingFlightSearch: 'Loading Flight Search...',
    popularRoutes: 'Popular Routes',
    fromPrice: 'From ${{price}}',
    // Subscriptions Page
    subscriptionsTitle: 'Choose Your Plan',
    subscriptionsSubtitle: 'Unlock more deals and exclusive perks with our subscription tiers.',
    currentPlan: 'Current Plan',
    subscribe: 'Unlock VIP Perks',
    dealRedemptions: 'deal redemptions per month',
    unlimitedDealRedemptions: 'Unlimited deal redemptions',
    // Login Page
    loginTitle: 'Login to Your Account',
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Access your deals and manage your subscription.',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    loginButton: 'Login',
    orContinueWith: 'Or continue with',
    signInWithGoogle: 'Continue with Google',
    signInWithFacebook: 'Continue with Facebook',
    signInWithApple: 'Continue with Apple',
    letsGetYouStarted: "Let's get you started",
    yourNextAdventure: "Your next adventure awaits.",
    continueWithEmail: "Continue with email",
    createAccount: 'Create Account',
    signupSubtitle: 'Join us today!',
    signupButton: 'Sign Up',
    alreadyHaveAccount: 'Already have an account? Login',
    dontHaveAccount: "Don't have an account? Sign Up",
    referralCodeOptional: 'Referral Code (Optional)',
    forgotPassword: 'Forgot password?',
    signupSuccess: 'Successfully signed up!',
    loginSuccess: 'Successfully logged in!',
    googleLoginError: 'Failed to sign in with Google.',
    facebookLoginError: 'Failed to sign in with Facebook.',
    appleLoginError: 'Failed to sign in with Apple.',
    businessPartners: 'Business Partners',
    partnerPortalEntrance: 'Access Partner Portal',
    becomePartner: 'Become a Partner',
    partnerPortalHint: 'Please login with your partner account to access the dashboard.',
    becomePartnerHint: 'Want to grow your business with Tripzy?',
    partnerAppTitle: 'Become a Tripzy Partner',
    partnerAppSubtitle: 'Please leave your details and we will reach out to you within 24 hours.',
    businessNameLabel: 'Business Name',
    contactNameLabel: 'Contact Name',
    industryLabel: 'Industry',
    messageLabel: 'Message (Optional)',
    submitApplication: 'Submit Application',
    partnerAppSuccess: 'Application submitted! We will contact you soon.',
    confirmDeleteCategory: 'Are you sure you want to delete category "{{name}}"? This might cause issues if deals are still assigned to it.',
    categoryDeletedSuccess: 'Category deleted successfully!',
    categorySaveError: 'Failed to save category. Please try again.',
    deleteUserConfirm: 'Are you sure you want to delete this user? This action cannot be undone.',
    userDeletedSuccess: 'User deleted successfully!',
    userUpdateSuccess: 'User updated successfully!',
    dealDeletedSuccess: 'Deal deleted successfully!',
    adminErrorTitle: 'Action Failed',
    adminSuccessTitle: 'Action Successful',
    confirmSyncPinecone: 'This will re-index ALL deals in Pinecone. This might take a while. Continue?',
    syncComplete: 'Sync complete!',
    syncFailed: 'Sync failed. Check console for details.',
    pineconeNotConfigured: 'Pinecone is not configured. Please add your API keys to environment variables.',
    importComplete: 'Import complete. Success: {success}, Failed: {errorCount}',
    provideTitleDesc: 'Please provide a Title and Description in at least one language (English or Turkish).',
    negativePriceError: 'Original Price cannot be negative.',
    discountPriceError: 'Discounted Price must be lower than the Original Price.',
    selectCategoryError: 'Please select a Category.',
    usageLimitError: 'Please provide Usage Limit in both English and Turkish.',
    validityError: 'Please provide Validity in both English and Turkish.',
    saveDealError: 'Failed to save deal. Please try again.',
    bulkDeleteConfirm: 'Are you sure you want to delete {count} deals?',
    bulkExpireConfirm: 'Set {count} deals to expired?',
    confirmResetHistory: 'WARNING: This will wipe ALL wallet items and redemption history for this user. Continue?',
    confirmVerifyEmail: 'Are you sure you want to manually verify this user\'s email?',
    confirmSendPush: 'Send a test push notification to this user?',
    redemptionsAddedSuccess: 'Extra redemptions added successfully!',

    termsAgreement: "By continuing, you agree to our",
    termsAgreementEnd: '.',
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    termsDescription: "Terms of Service for Tripzy. Please read carefully.",
    privacyDescription: "Privacy Policy for Tripzy - How we handle and protect your data.",
    and: "and",
    or: "OR",
    loginHeroBadge: "Over 10,000+ active travelers",
    loginHeroTitle: "Unlock the world's best travel secrets.",
    loginHeroSubtitle: "Join our community of explorers and get access to exclusive deals, hidden gems, and premium experiences at unbeatable prices.",
    // Deal Card
    expiresIn: 'Expires in',
    days: 'days',
    // FIX: Renamed 'day' to 'daySingular' to avoid duplicate key error.
    daySingular: 'day',
    expired: 'Expired',
    lockedDeal: 'Upgrade to',
    loginToUnlock: 'Login to unlock',
    toUnlock: 'to unlock',
    ratings: 'ratings',
    noRatingsYet: 'No ratings yet',
    neverExpires: 'Never expires',
    dealRequired: 'Required',
    // Bottom Navigation handled at the top
    // Profile Page
    profileTitle: 'Profile',
    profileSettingsTitle: 'Profile Settings',
    subscriptionStatus: 'Subscription Status',
    manageSubscription: 'Manage Subscription',
    settings: 'Settings',
    language: 'Language',
    currentLanguage: 'English',
    fullNameLabel: 'Full Name',
    saveChanges: 'Save Changes',
    profileUpdatedSuccess: 'Profile updated successfully!',
    premiumBadge: 'Premium',
    subscriptionInfo: 'Subscription Information',
    currentPlanLabel: 'Current Plan',
    planWithPrice: '{plan} Plan - {price}/mo',
    nextBillLabel: 'Next Bill',
    paymentMethodLabel: 'Payment Method',
    mobileLabel: 'Mobile Number',
    addressLabel: 'Address',
    addressPlaceholder: 'Enter your address',
    billingAddressLabel: 'Billing Address',
    billingAddressPlaceholder: 'Enter your billing address',
    redemptionsLeft: 'Redemptions Left',
    renewsOn: 'Renews On',
    managePlan: 'Manage Plan',
    upgradePlan: 'Upgrade Plan',
    accountSection: 'Account',
    profileInfo: 'Profile Information',
    personalInfo: 'Personal Information',
    billingHistory: 'Billing History',
    priceLabel: 'Price',
    resetsOn: 'Resets on',
    haveReferralCode: 'Have a referral code?',
    profileInfoSubtitle: 'Edit your personal information',
    changePassword: 'Change Password',
    changePasswordSubtitle: 'Update your account security',
    notificationSettings: 'Notification Settings',
    notificationSettingsSubtitle: 'Manage your notification preferences',
    languageSelection: 'Language Selection',
    appPreferencesSection: 'Application Preferences',
    locationServices: 'Location Services',
    locationServicesSubtitle: 'To see nearby deals',
    biometricAuth: 'Biometric Authentication',
    biometricAuthSubtitle: 'Fingerprint or face recognition',
    themeSelection: 'Theme Selection',
    themeSelectionSubtitle: 'Follow system settings',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    privacySection: 'Privacy',
    pushNotifications: 'Push Notifications',
    pushNotificationsSubtitle: 'Get timely alerts about deals',
    newDealNotifications: 'New Deal Alerts',
    expiringDealNotifications: 'Expiring Deal Reminders',
    darkMode: 'Dark Mode',
    notificationsDenied: 'Permissions denied. Please enable in browser settings.',
    // FIX: Renamed duplicate key 'privacyPolicy' to 'privacyPolicyLink' to avoid conflict with login page translation.
    privacyPolicyLink: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    deleteAccount: 'Delete Account',
    deleteAccountSubtitle: 'Permanently delete your account',
    supportSection: 'Support',
    helpCenter: 'Help Center',
    helpCenterSubtitle: 'FAQ and help articles',
    contact: 'Contact',
    contactSubtitle: 'Contact us',
    aboutApp: 'About Application',
    appVersion: 'Version 1.2.3 (Build 456)',
    signOut: 'Sign Out',
    changePasswordTitle: 'Change Password',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    passwordUpdateSuccess: 'Password updated successfully!',
    passwordMismatchError: 'Passwords do not match',
    passwordUpdateError: 'Failed to update password. Please try again.',
    checkoutTitle: 'Checkout',
    orderSummary: 'Order Summary',
    monthlySubscription: 'Monthly Subscription',
    total: 'Total',
    planFeatures: 'What\'s included:',
    paymentDetails: 'Payment Details',
    nameOnCard: 'Name on Card',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvc: 'CVC',
    payNow: 'Pay Now',
    processing: 'Processing...',
    securePayment: 'Payments are secure and encrypted',
    paymentSuccessful: 'Payment Successful!',
    paymentSuccessMessage: 'You have successfully upgraded to {{plan}}.',
    goToProfile: 'Go to Profile',
    backToHome: 'Back to Home',
    redirectingIn: 'Redirecting in {{seconds}} seconds...',
    upgradeTo: 'Upgrade to',
    amountDue: 'Amount Due Today',
    deleteAccountTitle: 'Delete Account',
    deleteAccountWarning: "Are you sure? This action is permanent and cannot be undone. All your data will be erased.",
    deleteAccountConfirmationPrompt: 'Please type "DELETE" to confirm.',
    confirmDeletion: 'Delete My Account',
    featureNotImplemented: 'This feature is not yet implemented.',
    uploadAPhoto: 'Upload a photo',
    referFriendTitle: 'Refer a Friend & Earn',
    referFriendSubtitle: 'Share your unique code with friends. They get a discount, and you get credits!',
    yourReferralCode: 'Your Referral Code',
    copyCode: 'Copy Code',
    copied: 'Copied!',
    bonusRedemptionsAvailable: 'Bonus Redemptions Available',
    // Trip Planner Page
    tripPlannerTitle: "AI Trip Planner",
    tripPlannerSubtitle: "Let our AI create a personalized itinerary for your next adventure.",
    destinationLabel: "Destination (e.g., Paris)",
    durationLabel: "Duration (in days)",
    interestsLabel: "What are your interests?",
    generateItinerary: "Generate Itinerary",
    generatingItinerary: "Generating your personalized itinerary... This may take a moment.",
    yourItinerary: "Your Personalized Itinerary for",
    // FIX: Renamed 'day' to 'tripPlannerDay' to avoid duplicate key error.
    tripPlannerDay: "Day",
    interestArt: "Art & Culture",
    interestFood: "Food & Cuisine",
    interestHistory: "History & Heritage",
    interestAdventure: "Adventure & Outdoors",
    interestNightlife: "Nightlife & Entertainment",
    interestShopping: "Shopping",
    // Deal Detail Page
    campaignConditions: 'Campaign Conditions',
    validLocations: 'Valid Locations',
    daysLeft: 'days left',
    rateThisDeal: 'Rate this deal',
    submitRating: 'Submit Rating',
    ratingSubmittedSuccess: 'Thank you for your rating!',
    redeemToRate: 'Redeem this deal to rate it',
    dealSaved: 'Saved',
    dealSave: 'Save',
    dealDetailsTitle: 'Deal Details',
    dealInformation: 'Deal Information',
    usageLimit: 'Usage Limit',
    validity: 'Validity',
    terms: 'Terms',
    seeFullTerms: 'See full terms and conditions',
    redeem: 'Claim Your Deal',
    redeemDealTitle: 'Redeem Deal',
    yourRedemptionCode: 'Your Redemption Code',
    close: 'Close',
    shareDeal: 'Share Deal',
    copyLink: 'Copy Link',
    instagramShareHint: 'Link copied! Paste it in your story or bio on Instagram.',
    // My Deals Page
    myDealsTitle: 'My Saved Deals',
    myDealsSubtitle: 'All your saved deals in one place.',
    noSavedDeals: 'You haven\'t saved any deals yet. Start exploring!',
    saveDealAction: 'Save Deal',
    unsaveDealAction: 'Unsave Deal',
    // Wallet Page
    myWalletTitle: 'My Wallet',
    myWalletSubtitle: 'Deals you have purchased or won',
    emptyWallet: 'Your wallet is empty',
    browseDeals: 'Browse Deals',
    walletFilterAll: 'All',
    walletFilterActive: 'Active',
    walletFilterRedeemed: 'Used',
    walletFilterExpired: 'Expired',
    walletStatusActive: 'Active',
    walletStatusRedeemed: 'Used',
    walletStatusExpired: 'Expired',
    walletExpiresIn: 'Expires in',
    walletSortRecent: 'Recently Added',
    walletSortExpiring: 'Expiring Soon',
    walletSortValue: 'Highest Value',
    walletCapacity: 'Wallet Capacity',
    walletCapacityUsed: 'deals in wallet',
    walletCapacityFull: 'Wallet Full!',
    walletCapacityNearFull: 'Almost Full',
    walletCapacityUnlimited: 'Unlimited',
    walletUpgradePrompt: 'Upgrade to add more deals',
    walletLimitReached: 'You have reached your wallet limit',
    walletLimitReachedDesc: 'Please upgrade your plan or remove some deals to add more.',
    // Admin Page
    adminDashboard: 'Admin Dashboard',
    manageDeals: 'Manage Deals',
    manageUsers: 'Manage Users',
    addDeal: 'Add New Deal',
    editDeal: 'Edit Deal',
    editUser: 'Edit User',
    dealTypeLabel: 'Deal Type',
    timeTypeLabel: 'Time / Duration Type',
    flashDealLabel: 'Flash Deal',
    flashEndTimeLabel: 'Flash Deal End Time',
    titleLabel: 'Title (EN)',
    titleTrLabel: 'Title (TR)',
    descriptionLabel: 'Description (EN)',
    descriptionTrLabel: 'Description (TR)',
    imageUrlLabel: 'Image URL',
    imageUrlOptionalHint: '(Optional, AI will generate if left blank)',
    categoryLabel: 'Category',
    originalPriceLabel: 'Original Price ($)',
    discountPercentageLabel: 'Discount (%)',
    readMore: 'Read more',
    readLess: 'Daha az göster',
    offerDetails: 'Offer Details',
    useCoupon: 'Use Coupon',
    yourCouponCode: 'Your Coupon Code',
    showThisCodeAtCheckout: 'Show this code at checkout',

    viewTermsAndConditions: 'View Terms & Conditions',
    discount: 'Discount',
    discountedPriceLabel: 'Discounted Price ($)',
    requiredTierLabel: 'Required Tier',
    vendorLabel: 'Vendor / Place Name',
    expiresInDaysLabel: 'Expires In (Days)',
    usageLimitLabel: 'Usage Limit (e.g., One per person)',
    usageLimitTrLabel: 'Usage Limit (Turkish)',
    validityLabel: 'Validity (e.g., Weekdays only)',
    validityTrLabel: 'Validity (Turkish)',
    termsUrlLabel: 'Terms & Conditions (URL or Text)',
    redemptionCodeLabel: 'Redemption Code (Secret)',
    saveDeal: 'Save Deal',
    updateDeal: 'Update Deal',
    saving: 'Saving...',
    generatingImage: 'Generating Image...',
    cancel: 'Cancel',
    deleteDeal: 'Delete',
    deleteConfirmation: 'Are you sure you want to delete this deal?',
    deleteUserConfirmation: 'Are you sure you want to delete this user?',
    off: 'OFF',
    adminAnalytics: 'Analytics',
    adminContent: 'Manage Content',
    adminFlightRoutes: 'Flight Routes',
    adminPaymentTransactions: 'Payment Transactions',
    adminPendingApprovals: 'Pending Approvals',
    adminAnnouncements: 'Announcements',
    adminSubscriptions: 'Subscriptions',
    allDeals: 'All Deals',
    allUsers: 'All Users',
    tier: 'Tier',
    actions: 'Actions',
    updateUser: 'Update User',
    manageSavedDeals: 'Manage Saved Deals',
    noSavedDealsForUser: 'This user has no saved deals.',
    addDealToUser: 'Add Deal to User',
    selectDeal: 'Select a deal...',
    add: 'Add',
    remove: 'Remove',
    referredByLabel: 'Referred By',
    usersReferredLabel: 'Users Referred',
    referralChainLabel: 'Referral Chain',
    referralNetworkLabel: 'Referral Network',
    topOfChain: 'Top of chain',
    noNetwork: 'This user has not referred anyone.',
    addExtraRedemptions: 'Add Extra Redemptions',
    currentBonusRedemptions: 'Current Bonus Redemptions',
    redemptionsToAdd: 'Number to Add',
    addRedemptions: 'Add',
    // AI Chatbot
    aiDealFinderTitle: 'AI Deal Finder',
    aiGreeting: 'Hello! How can I help you find the perfect deal today? You can ask me things like "find me a relaxing spa deal" or "show me top-rated travel deals".',
    aiChatPlaceholder: 'Ask about deals...',
    // Ad Banner
    advertisement: 'Advertisement',
    // Notifications
    newDealNotificationTitle: 'New Deal Available!',
    expiringDealNotificationTitle: 'Deal Expiring Soon!',
    expiringDealNotificationBody: 'Your saved deal \'{dealTitle}\' expires in 1 day.',
    // Terms and Conditions
    generalTerms: 'General Terms',
    termsPoint1: 'This offer is valid only for registered users with the required subscription tier.',
    termsPoint2: 'The deal cannot be combined with other offers or promotions.',
    termsPoint3: 'The vendor reserves the right to refuse service if terms are violated.',
    termsPoint4: 'Redemption codes are single-use and non-transferable.',
    // Redemption Warning
    redemptionWarningTitle: 'Confirm Redemption',
    redemptionWarningBody: 'This will use one of your monthly redemptions. Are you sure you want to proceed?',
    dontShowAgain: "Don't show this again",
    confirmRedeem: 'Redeem',
    cancelRedeem: 'Cancel',
    recommendedForYou: 'Recommended for You',
    startExploringForRecommendations: 'Start exploring deals to get personalized recommendations!',
    redeemNow: 'Redeem Now',
    addToWallet: 'Add to Wallet',
    addToWalletShort: 'Add',
    failedToClaimDeal: 'Failed to add deal to wallet.',
    dealSoldOutAlert: 'This deal is currently sold out.',
    confirmAddToWallet: 'Add to Wallet',
    // Limit Reached Modal
    limitReachedTitle: 'Limit Reached',
    monthlyLimitReached: 'Monthly Limit Reached',
    upgradePrompt: 'You have used all your redemptions for this month. Upgrade your plan to unlock more amazing deals!',
    upgradePlanButton: 'Upgrade Plan',
    maybeLater: 'Maybe Later',
    // Admin Sidebar
    adminSidebarOverview: 'Overview',
    adminSidebarManagement: 'Management',
    adminSidebarSystem: 'System',
    adminSidebarFinance: 'Finance',
    adminCategories: 'Categories',
    adminVendorReports: 'Vendor Reports',
    adminBackgrounds: 'Backgrounds',
    adminPromoCodes: 'Promo Codes',
    adminAuditLogs: 'Audit Logs',
    adminBackToApp: 'Back to App',
    // Footer
    footerText: '© 2024 Tripzy. All rights reserved.',
  },
  tr: {
    // Header
    navHome: 'Anasayfa',
    navSubscriptions: 'Abonelikler',
    login: 'Giriş Yap',
    logout: 'Çıkış Yap',
    bottomNavHome: 'Anasayfa',
    bottomNavTravel: 'Seyahat',
    bottomNavWallet: 'Cüzdan',
    bottomNavProfile: 'Profil',
    bottomNavAdmin: 'Yönetim',
    bottomNavWishlist: 'İstek Listesi',
    collectionHubTitle: 'Koleksiyon',
    collectionHubSubtitle: 'Aktif fırsatlar ve istek listeniz için kişisel merkeziniz',
    walletTabActive: 'Aktif',
    walletTabHistory: 'Geçmiş',
    walletUseNow: 'Hemen Kullan',
    walletExpiresToday: 'Bugün Sona Eriyor',
    walletExpiresSoon: 'Yakında Sona Eriyor',
    flightsMovedTitle: 'Uçuşlar artık Seyahat Merkezi\'nde',
    flightsMovedSubtitle: 'Tüm seyahatle ilgili özellikleri yeni özel bölümümüze taşıdık.',
    goToTravelHub: 'Seyahat Merkezi\'ne Git',
    onboardingWelcome: 'Tripzy\'ye Hoş Geldiniz! ✨',
    onboardingTravelStyleQuestion: 'İdeal seyahat tarzınız nedir?',
    onboardingBudgetQuestion: 'Bütçe tercihiniz nedir?',
    onboardingBudgetSubtitle: 'Tarzınıza en uygun fırsatları göstereceğiz',
    onboardingBenefit1Title: 'Özel Fırsatları Keşfet',
    onboardingBenefit1Desc: 'Binlerce premium seyahat indirimine erişin.',
    onboardingBenefit2Title: 'Kolay Kullanım',
    onboardingBenefit2Desc: 'Kupon kodunuzu alın ve anında kullanın.',
    onboardingBenefit3Title: 'Üyelik Avantajları',
    onboardingBenefit3Desc: 'Daha fazla tasarruf için yükseltin.',
    skip: 'Atla',
    next: 'İleri',
    back: 'Geri',
    getStarted: 'Başlayalım',
    budgetBudget: 'Bütçe Dostu',
    budgetBudgetDesc: 'En iyi fiyatlı fırsatlar',
    budgetModerate: 'Orta',
    budgetModerateDesc: 'Kalite ve konfor',
    budgetLuxury: 'Lüks',
    budgetLuxuryDesc: 'Premium deneyimler',
    travelStyleBeach: 'Plaj & Rahatlama',
    travelStyleMountain: 'Dağ & Doğa',
    travelStyleCity: 'Şehir & Kültür',
    travelStyleAdventure: 'Macera & Spor',
    onboardingQuote: 'Seyahat, satın alıp da sizi zenginleştiren tek şeydir.',
    onboardingTravelStyleSubtitle: 'Sizi en çok ne heyecanlandırır? Birini veya birkaçını seçin.',
    welcome: 'Hoş geldiniz',
    searchPlaceholder: 'Fırsatları ara',
    // Personalized Greetings
    greetingMorning: 'Günaydın',
    greetingAfternoon: 'İyi günler',
    greetingEvening: 'İyi akşamlar',
    greetingNight: 'İyi geceler',
    greetingSubtitleMorning: "Güne harika fırsatlarla başlayın! ☀️",
    greetingSubtitleAfternoon: "İşte bugünün sizin için en iyi seçimleri 🌤️",
    greetingSubtitleEvening: "Bu özel tekliflerle rahatlayın 🌙",
    greetingSubtitleNight: "Sadece sizin için gece fırsatları 🌟",
    // Home Page
    heroTitle: 'Dünya Çapında Özel Seyahat Fırsatları',
    heroSubtitle: 'Dünya genelinde lüks oteller, uçuşlar ve restoranlarda %70\'e varan indirimleri keşfedin.',
    homeTitle: 'Tripzy - Global Seyahat Fırsatları ve İndirimleri',
    homeDescription: 'Tripzy ile dünya çapında otel, uçuş ve restoranlarda özel indirimleri keşfedin. En iyi seyahat fırsatları parmaklarınızın ucunda.',
    featuredDeals: 'Öne Çıkan Fırsatlar',
    noResults: 'Aramanızla eşleşen fırsat bulunamadı.',
    recentSearches: 'Son Aramalar',
    clear: 'Temizle',
    noRecentSearches: 'Son arama yok.',
    filterByRating: 'Puana Göre Filtrele',
    allRatings: 'Tümü',
    // Categories
    categoryAll: 'Tümü',
    categoryFlights: 'Uçuşlar',
    categoryDining: 'Yemek',
    categoryWellness: 'Sağlık',
    categoryTravel: 'Seyahat',
    faqTitle: 'Tripzy - Yardım Merkezi ve Sıkça Sorulan Sorular',
    faqDescription: 'Tripzy abonelikleri, fırsat kullanımı ve seyahat hizmetleri hakkında bilmeniz gereken her şey.',
    flightsPageTitle: 'Uçak Bileti Fırsatları - Tripzy',
    flightsPageDescription: 'Global uçuşlarda en iyi indirimleri keşfedin. Tripzy ile her uçuşta tasarruf edin.',
    travelPageTitle: 'Özel Seyahat Fırsatları - Tripzy',
    travelPageDescription: 'Dünya çapında otel ve tatil köylerinde size özel konaklama fırsatları.',
    findFlightsTitle: 'UÇUŞ KEŞFİ',
    loadingFlightSearch: 'Uçuş Araması Yükleniyor...',
    popularRoutes: 'Popüler Rotalar',
    fromPrice: '₺{{price}}\'den Başlayan Fiyatlarla',
    // Subscriptions Page
    subscriptionsTitle: 'Planınızı Seçin',
    subscriptionsSubtitle: 'Abonelik seviyelerimizle daha fazla fırsatın ve özel avantajların kilidini açın.',
    currentPlan: 'Mevcut Plan',
    subscribe: 'VIP Ayrıcalıklarını Keşfedin',
    dealRedemptions: 'aylık fırsat kullanım hakkı',
    unlimitedDealRedemptions: 'Sınırsız fırsat kullanımı',
    // Login Page
    loginTitle: 'Hesabınıza Giriş Yapın',
    welcomeBack: 'Tekrar Hoşgeldiniz',
    loginSubtitle: 'Fırsatlarınıza erişin ve aboneliğinizi yönetin.',
    emailLabel: 'E-posta Adresi',
    passwordLabel: 'Şifre',
    loginButton: 'Giriş Yap',
    orContinueWith: 'Veya şununla devam et',
    signInWithGoogle: 'Google ile devam et',
    signInWithFacebook: 'Facebook ile devam et',
    signInWithApple: 'Apple ile devam et',
    letsGetYouStarted: "Haydi başlayalım",
    yourNextAdventure: "Yeni maceranız sizi bekliyor.",
    continueWithEmail: "E-posta ile devam et",
    createAccount: 'Hesap Oluştur',
    signupSubtitle: 'Bugün bize katılın!',
    signupButton: 'Kayıt Ol',
    alreadyHaveAccount: 'Zaten hesabınız var mı? Giriş Yapın',
    dontHaveAccount: "Hesabınız yok mu? Kayıt Olun",
    referralCodeOptional: 'Davet Kodu (İsteğe Bağlı)',
    forgotPassword: 'Şifremi unuttum?',
    signupSuccess: 'Başarıyla kayıt olundu!',
    loginSuccess: 'Başarıyla giriş yapıldı!',
    googleLoginError: 'Google ile giriş yapılamadı.',
    facebookLoginError: 'Facebook ile giriş yapılamadı.',
    appleLoginError: 'Apple ile giriş yapılamadı.',
    businessPartners: 'İş Ortakları',
    partnerPortalEntrance: 'Partner Paneline Giriş',
    becomePartner: 'Partnerimiz Olun',
    partnerPortalHint: 'Lütfen kullanıcı bilgilerinizle giriş yapın; sistem sizi otomatik olarak iş ortağı paneline yönlendirecektir.',
    becomePartnerHint: 'İşletmenizi Tripzy ile büyütmek ister misiniz?',
    partnerAppTitle: 'Tripzy Partneri Olun',
    partnerAppSubtitle: 'Bilgilerinizi bırakın, 24 saat içinde sizinle iletişime geçelim.',
    businessNameLabel: 'İşletme Adı',
    contactNameLabel: 'Yetkili Adı',
    industryLabel: 'Sektör',
    messageLabel: 'Mesajınız (İsteğe Bağlı)',
    submitApplication: 'Başvuruyu Gönder',
    partnerAppSuccess: 'Başvurunuz alındı! Yakında sizinle iletişime geçeceğiz.',
    confirmDeleteCategory: '"{{name}}" kategorisini silmek istediğinizden emin misiniz? Bu kategoriye bağlı fırsatlar varsa sorun oluşabilir.',
    categoryDeletedSuccess: 'Kategori başarıyla silindi!',
    categorySaveError: 'Kategori kaydedilemedi. Lütfen tekrar deneyin.',
    deleteUserConfirm: 'Bu kullanıcıyı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    userDeletedSuccess: 'Kullanıcı başarıyla silindi!',
    userUpdateSuccess: 'Kullanıcı başarıyla güncellendi!',
    dealDeletedSuccess: 'Fırsat başarıyla silindi!',
    adminErrorTitle: 'İşlem Başarısız',
    adminSuccessTitle: 'İşlem Başarılı',
    confirmSyncPinecone: 'Bu işlem TÜM fırsatları Pinecone\'da yeniden indeksleyecektir. Bu işlem biraz zaman alabilir. Devam edilsin mi?',
    syncComplete: 'Senkronizasyon tamamlandı!',
    syncFailed: 'Senkronizasyon başarısız oldu. Detaylar için konsolu kontrol edin.',
    pineconeNotConfigured: 'Pinecone yapılandırılmamış. Lütfen API anahtarlarınızı ortam değişkenlerine ekleyin.',
    importComplete: 'İçe aktarma tamamlandı. Başarılı: {success}, Başarısız: {errorCount}',
    provideTitleDesc: 'Lütfen en az bir dilde (İngilizce veya Türkçe) bir Başlık ve Açıklama girin.',
    negativePriceError: 'Orijinal Fiyat negatif olamaz.',
    discountPriceError: 'İndirimli Fiyat, Orijinal Fiyat\'tan düşük olmalıdır.',
    selectCategoryError: 'Lütfen bir Kategori seçin.',
    usageLimitError: 'Lütfen Kullanım Sınırını hem İngilizce hem de Türkçe olarak girin.',
    validityError: 'Lütfen Geçerliliği hem İngilizce hem de Türkçe olarak girin.',
    saveDealError: 'Fırsat kaydedilemedi. Lütfen tekrar deneyin.',
    bulkDeleteConfirm: '{count} fırsatı silmek istediğinizden emin misiniz?',
    bulkExpireConfirm: '{count} fırsatı süresi dolmuş olarak işaretle?',
    confirmResetHistory: 'UYARI: Bu işlem bu kullanıcının TÜM cüzdan öğelerini ve kullanım geçmişini silecektir. Devam edilsin mi?',
    confirmVerifyEmail: 'Bu kullanıcının e-postasını manuel olarak doğrulamak istediğinizden emin misiniz?',
    confirmSendPush: 'Bu kullanıcıya test bildirimi gönderilsin mi?',
    redemptionsAddedSuccess: 'Ekstra kullanım hakları başarıyla eklendi!',

    termsAgreement: "Devam ederek,",
    termsAgreementEnd: ' kabul etmiş olursunuz.',
    termsOfService: "Kullanım Koşullarımızı",
    privacyPolicy: "Gizlilik Politikamızı",
    termsDescription: "Tripzy Kullanım Koşulları. Lütfen dikkatlice okuyunuz.",
    privacyDescription: "Tripzy Gizlilik Politikası - Verilerinizi nasıl koruduğumuzu ve işlediğimizi öğrenin.",
    and: "ve",
    or: "VEYA",
    loginHeroBadge: "10.000'den fazla aktif gezgin",
    loginHeroTitle: "Dünyanın en iyi seyahat sırlarını keşfedin.",
    loginHeroSubtitle: "Kaşifler topluluğumuza katılın; özel fırsatlara, gizli kalmış güzelliklere ve eşsiz deneyimlere rakipsiz fiyatlarla erişin.",
    // Deal Card
    expiresIn: 'Son',
    days: 'gün',
    // FIX: Renamed 'day' to 'daySingular' to avoid duplicate key error.
    daySingular: 'gün',
    expired: 'Süresi Doldu',
    lockedDeal: 'Yükselt',
    loginToUnlock: 'Kilidi açmak için giriş yap',
    toUnlock: 'açmak için',
    ratings: 'değerlendirme',
    noRatingsYet: 'Henüz değerlendirme yok',
    neverExpires: 'Süresi Dolmaz',
    dealRequired: 'Gerekli',
    // Bottom Navigation
    // Alt Gezinme yukarda tanımlandı
    // Profile Page
    profileTitle: 'Profil',
    profileSettingsTitle: 'Profil Ayarları',
    subscriptionStatus: 'Abonelik Durumu',
    manageSubscription: 'Aboneliği Yönet',
    settings: 'Ayarlar',
    language: 'Dil',
    currentLanguage: 'Türkçe',
    fullNameLabel: 'Tam Ad',
    saveChanges: 'Değişiklikleri Kaydet',
    profileUpdatedSuccess: 'Profil başarıyla güncellendi!',
    premiumBadge: 'Premium',
    subscriptionInfo: 'Abonelik Bilgileri',
    currentPlanLabel: 'Mevcut Plan',
    planWithPrice: '{plan} Paket - {price} TL/ay',
    nextBillLabel: 'Sonraki Fatura',
    paymentMethodLabel: 'Ödeme Yöntemi',
    mobileLabel: 'Cep Telefonu',
    addressLabel: 'Adres',
    addressPlaceholder: 'Adresinizi girin',
    billingAddressLabel: 'Fatura Adresi',
    billingAddressPlaceholder: 'Fatura adresinizi girin',
    redemptionsLeft: 'Kalan Kullanım Hakkı',
    renewsOn: 'Yenilenme Tarihi',
    managePlan: 'Planı Yönet',
    upgradePlan: 'Plan Yükselt',
    accountSection: 'Hesap',
    profileInfo: 'Profil Bilgileri',
    personalInfo: 'Kişisel Bilgiler',
    billingHistory: 'Ödeme Geçmişi',
    priceLabel: 'Fiyat',
    resetsOn: 'Sıfırlanma:',
    haveReferralCode: 'Davet kodunuz var mı?',
    profileInfoSubtitle: 'Kişisel bilgilerinizi düzenleyin',
    changePassword: 'Şifre Değiştir',
    changePasswordSubtitle: 'Hesap güvenliğinizi güncelleyin',
    notificationSettings: 'Bildirim Ayarları',
    notificationSettingsSubtitle: 'Bildirim tercihlerinizi yönetin',

    languageSelection: 'Dil Seçimi',
    appPreferencesSection: 'Uygulama Tercihleri',
    locationServices: 'Konum Servisleri',
    locationServicesSubtitle: 'Yakındaki fırsatları görmek için',
    biometricAuth: 'Biyometrik Kimlik Doğrulama',
    biometricAuthSubtitle: 'Parmak izi veya yüz tanıma',
    themeSelection: 'Tema Seçimi',
    themeSelectionSubtitle: 'Sistem ayarını takip et',
    themeLight: 'Açık',
    themeDark: 'Koyu',
    themeSystem: 'Sistem',
    privacySection: 'Gizlilik',
    pushNotifications: 'Anlık Bildirimler',
    pushNotificationsSubtitle: 'Fırsatlar hakkında zamanında uyarılar alın',
    newDealNotifications: 'Yeni Fırsat Uyarıları',
    expiringDealNotifications: 'Süresi Dolan Fırsat Hatırlatıcıları',
    darkMode: 'Karanlık Mod',
    notificationsDenied: 'İzinler reddedildi. Lütfen tarayıcı ayarlarından etkinleştirin.',
    // FIX: Renamed duplicate key 'privacyPolicy' to 'privacyPolicyLink' to avoid conflict with login page translation.
    privacyPolicyLink: 'Gizlilik Politikası',
    termsOfUse: 'Kullanım Şartları',
    deleteAccount: 'Hesabı Sil',
    deleteAccountSubtitle: 'Hesabınızı kalıcı olarak silin',
    supportSection: 'Destek',
    helpCenter: 'Yardım Merkezi',
    helpCenterSubtitle: 'SSS ve yardım makaleleri',
    contact: 'İletişim',
    contactSubtitle: 'Bize ulaşın',
    aboutApp: 'Tripzy Hakkında',
    appVersion: 'Sürüm 1.2.3 (Sunucu v456)',
    signOut: 'Güvenli Çıkış',
    changePasswordTitle: 'Şifre Değiştir',
    currentPasswordLabel: 'Mevcut Şifre',
    newPasswordLabel: 'Yeni Şifre',
    confirmNewPasswordLabel: 'Yeni Şifreyi Onayla',
    passwordUpdateSuccess: 'Şifre başarıyla güncellendi!',
    passwordMismatchError: 'Şifreler eşleşmiyor.',
    passwordUpdateError: 'Şifre güncellenemedi. Lütfen tekrar deneyin.',
    checkoutTitle: 'Ödeme',
    orderSummary: 'Sipariş Özeti',
    monthlySubscription: 'Aylık Üyelik',
    total: 'Toplam Ödenecek',
    planFeatures: 'Abonelik Ayrıcalıkları:',
    paymentDetails: 'Ödeme Bilgileri',
    nameOnCard: 'Kart Sahibinin Adı',
    cardNumber: 'Kart Numarası',
    expiryDate: 'Son Kullanma Tarihi',
    cvc: 'CVC',
    payNow: 'Şimdi Öde',
    processing: 'İşleniyor...',
    securePayment: 'Ödemeler güvenli ve şifrelidir',
    paymentSuccessful: 'Ödeme Başarılı!',
    paymentSuccessMessage: 'Başarıyla {{plan}} paketine geçiş yaptınız.',
    goToProfile: 'Profile Git',
    backToHome: 'Ana Sayfaya Dön',
    redirectingIn: '{{seconds}} saniye içinde yönlendiriliyorsunuz...',
    upgradeTo: 'Yükseltme',
    amountDue: 'Bugün Ödenecek Tutar',
    deleteAccountTitle: 'Hesabı Sil',
    deleteAccountWarning: "Emin misiniz? Bu işlem kalıcıdır ve geri alınamaz. Tüm verileriniz silinecektir.",
    deleteAccountConfirmationPrompt: 'Onaylamak için lütfen "SİL" yazın.',
    confirmDeletion: 'Hesabımı Sil',
    featureNotImplemented: 'Bu özellik henüz uygulanmadı.',
    uploadAPhoto: 'Fotoğraf yükle',
    referFriendTitle: 'Arkadaşını Davet Et & Kazan',
    referFriendSubtitle: 'Benzersiz kodunu arkadaşlarınla paylaş. Onlar indirim kazanırken, sen de kredi kazan!',
    yourReferralCode: 'Davet Kodun',
    copyCode: 'Kodu Kopyala',
    copied: 'Kopyalandı!',
    bonusRedemptionsAvailable: 'Bonus Kullanım Hakkı Mevcut',
    // Trip Planner Page
    tripPlannerTitle: "Yapay Zeka Gezi Planlayıcısı",
    tripPlannerSubtitle: "Bir sonraki maceranız için yapay zekamızın kişiselleştirilmiş bir güzergah oluşturmasına izin verin.",
    destinationLabel: "Varış Yeri (örn. Paris)",
    durationLabel: "Süre (gün olarak)",
    interestsLabel: "İlgi alanlarınız neler?",
    generateItinerary: "Güzergah Oluştur",
    generatingItinerary: "Kişiselleştirilmiş güzergahınız oluşturuluyor... Bu biraz zaman alabilir.",
    yourItinerary: "için Kişiselleştirilmiş Güzergahınız",
    // FIX: Renamed 'day' to 'tripPlannerDay' to avoid duplicate key error.
    tripPlannerDay: "Gün",
    interestArt: "Sanat ve Kültür",
    interestFood: "Yemek ve Mutfak",
    interestHistory: "Tarih ve Miras",
    interestAdventure: "Macera ve Doğa",
    interestNightlife: "Gece Hayatı ve Eğlence",
    interestShopping: "Alışveriş",
    // Deal Detail Page
    campaignConditions: 'Kampanya Koşulları',
    validLocations: 'Geçerli Lokasyonlar',
    daysLeft: 'Gün Kaldı',
    rateThisDeal: 'Bu fırsatı değerlendir',
    submitRating: 'Değerlendirmeyi Gönder',
    ratingSubmittedSuccess: 'Değerlendirmeniz için teşekkür ederiz!',
    redeemToRate: 'Değerlendirmek için bu fırsatı kullanın',
    dealSaved: 'Kaydedildi',
    dealSave: 'Kaydet',
    dealDetailsTitle: 'Fırsat Detayları',
    dealInformation: 'Fırsat Bilgileri',
    usageLimit: 'Kullanım Limiti',
    validity: 'Geçerlilik',
    terms: 'Koşullar',
    seeFullTerms: 'Tüm şartlar ve koşulları gör',
    redeem: 'Kullan',
    redeemDealTitle: 'Fırsatı Kullan',
    yourRedemptionCode: 'Kullanım Kodunuz',
    close: 'Kapat',
    shareDeal: 'Fırsatı Paylaş',
    copyLink: 'Bağlantıyı Kopyala',
    instagramShareHint: 'Bağlantı kopyalandı! Instagram hikayenize veya biyografinize yapıştırın.',
    // My Deals Page
    myDealsTitle: 'Kaydedilen Fırsatlarım',
    myDealsSubtitle: 'Tüm kayıtlı fırsatlarınız tek bir yerde.',
    noSavedDeals: 'Henüz hiç fırsat kaydetmediniz. Keşfetmeye başlayın!',
    saveDealAction: 'Fırsatı Kaydet',
    unsaveDealAction: 'Kaydedileni Kaldır',
    // Wallet Page
    myWalletTitle: 'Cüzdanım',
    myWalletSubtitle: 'Satın aldığınız veya kazandığınız fırsatlar',
    emptyWallet: 'Cüzdanınız boş',
    browseDeals: 'Fırsatlara Göz At',
    walletFilterAll: 'Tümü',
    walletFilterActive: 'Aktif',
    walletFilterRedeemed: 'Kullanıldı',
    walletFilterExpired: 'Süresi Doldu',
    walletSavingsSummary: 'Toplam tasarrufunuz',
    walletTotalSavings: 'Toplam Tasarruf',
    walletCapacityUnlimited: 'Sınırsız',
    walletUpgradePrompt: 'Daha fazla fırsat eklemek için yükseltin',
    walletLimitReached: 'Cüzdan limitinize ulaştınız',
    dealSoldOutAlert: 'Bu fırsat şu anda tükenmiş durumda.',
    walletLimitReachedDesc: 'Daha fazla eklemek için planınızı yükseltin veya bazı fırsatları kaldırın.',
    // Admin Page
    adminDashboard: 'Yönetici Paneli',
    manageDeals: 'Fırsatları Yönet',
    manageUsers: 'Kullanıcıları Yönet',
    addDeal: 'Yeni Fırsat Ekle',
    editDeal: 'Fırsatı Düzenle',
    editUser: 'Kullanıcıyı Düzenle',
    titleLabel: 'Başlık (EN)',
    titleTrLabel: 'Başlık (TR)',
    descriptionLabel: 'Açıklama (EN)',
    descriptionTrLabel: 'Açıklama (TR)',
    imageUrlLabel: 'Görsel URL\'si',
    imageUrlOptionalHint: '(İsteğe bağlı, boş bırakılırsa YZ oluşturur)',
    categoryLabel: 'Kategori',
    originalPriceLabel: 'Orijinal Fiyat ($)',
    discountPercentageLabel: 'İndirim (%)',
    readMore: 'Devamını oku',
    readLess: 'Daha az göster',
    offerDetails: 'Fırsat Detayları',
    useCoupon: 'Kuponu Kullan',
    yourCouponCode: 'Kupon Kodunuz',
    showThisCodeAtCheckout: 'Bu kodu ödeme sırasında gösterin',

    viewTermsAndConditions: 'Şartlar ve Koşulları Görüntüle',
    discount: 'İndirim',
    dealTypeLabel: 'Fırsat Tipi',
    timeTypeLabel: 'Süre Tipi',
    flashDealLabel: 'Flaş Fırsat',
    flashEndTimeLabel: 'Flaş Fırsat Bitiş Zamanı',
    discountedPriceLabel: 'İndirimli Fiyat ($)',
    requiredTierLabel: 'Gerekli Seviye',
    vendorLabel: 'Satıcı / Mekan Adı',
    expiresInDaysLabel: 'Bitiş Süresi (Gün)',
    usageLimitLabel: 'Kullanım Limiti (örn. Kişi başı bir)',
    usageLimitTrLabel: 'Kullanım Limiti (Türkçe)',
    validityLabel: 'Geçerlilik (örn. Sadece hafta içi)',
    validityTrLabel: 'Geçerlilik (Türkçe)',
    termsUrlLabel: 'Şartlar ve Koşullar (URL veya Metin)',
    redemptionCodeLabel: 'Kullanım Kodu (Gizli)',
    saveDeal: 'Fırsatı Kaydet',
    updateDeal: 'Fırsatı Güncelle',
    saving: 'Kaydediliyor...',
    generatingImage: 'Görsel Oluşturuluyor...',
    cancel: 'İptal',
    deleteDeal: 'Sil',
    deleteConfirmation: 'Bu fırsatı silmek istediğinizden emin misiniz?',
    deleteUserConfirmation: 'Bu kullanıcıyı silmek istediğinizden emin misiniz?',
    off: 'İNDİRİM',
    adminAnalytics: 'Analitik',
    adminContent: 'İçerik Yönetimi',
    adminFlightRoutes: 'Uçuş Rotaları',
    adminPaymentTransactions: 'Ödeme İşlemleri',
    adminPendingApprovals: 'Bekleyen Onaylar',
    adminAnnouncements: 'Duyurular',
    adminSubscriptions: 'Abonelikler',
    allDeals: 'Tüm Fırsatlar',
    allUsers: 'Tüm Kullanıcılar',
    tier: 'Seviye',
    actions: 'Eylemler',
    updateUser: 'Kullanıcıyı Güncelle',
    manageSavedDeals: 'Kayıtlı Fırsatları Yönet',
    noSavedDealsForUser: 'Bu kullanıcının kayıtlı fırsatı yok.',
    addDealToUser: 'Kullanıcıya Fırsat Ekle',
    selectDeal: 'Bir fırsat seçin...',
    add: 'Ekle',
    remove: 'Kaldır',
    referredByLabel: 'Tavsiye Eden',
    usersReferredLabel: 'Tavsiye Edilen Kullanıcılar',
    referralChainLabel: 'Tavsiye Zinciri',
    referralNetworkLabel: 'Tavsiye Ağı',
    topOfChain: 'Zincirin başı',
    noNetwork: 'Bu kullanıcı kimseyi tavsiye etmedi.',
    addExtraRedemptions: 'Ekstra Kullanım Hakkı Ekle',
    currentBonusRedemptions: 'Mevcut Bonus Kullanım Hakları',
    redemptionsToAdd: 'Eklenecek Sayı',
    addRedemptions: 'Ekle',
    // AI Chatbot
    aiDealFinderTitle: 'YZ Fırsat Bulucu',
    aiGreeting: 'Merhaba! Bugün mükemmel fırsatı bulmanıza nasıl yardımcı olabilirim? Bana "rahatlatıcı bir spa fırsatı bul" veya "en yüksek puanlı seyahat fırsatlarını göster" gibi şeyler sorabilirsiniz.',
    aiChatPlaceholder: 'Fırsatlar hakkında soru sor...',
    // Ad Banner
    advertisement: 'Reklam',
    // Notifications
    newDealNotificationTitle: 'Yeni Fırsat Mevcut!',
    expiringDealNotificationTitle: 'Fırsatın Süresi Dolmak Üzere!',
    expiringDealNotificationBody: 'Kaydedilen \'{dealTitle}\' fırsatınızın süresi 1 gün içinde doluyor.',
    // Terms and Conditions
    generalTerms: 'Genel Koşullar',
    termsPoint1: 'Bu teklif yalnızca gerekli abonelik seviyesine sahip kayıtlı kullanıcılar için geçerlidir.',
    termsPoint2: 'Fırsat diğer teklifler veya promosyonlarla birleştirilemez.',
    termsPoint3: 'Satıcı, şartların ihlal edilmesi durumunda hizmeti reddetme hakkını saklı tutar.',
    termsPoint4: 'Kullanım kodları tek kullanımlıktır ve devredilemez.',
    // Admin Sidebar
    adminSidebarOverview: 'Genel Bakış',
    adminSidebarManagement: 'Yönetim',
    adminSidebarSystem: 'Sistem',
    adminSidebarFinance: 'Finans',
    adminCategories: 'Kategoriler',
    adminVendorReports: 'Partner Raporları',
    adminBackgrounds: 'Arka Planlar',
    adminPromoCodes: 'Promosyon Kodları',
    adminAuditLogs: 'Denetim Günlükleri',
    adminBackToApp: 'Uygulamaya Dön',
    // Redemption Modal
    redemptionWarningTitle: 'Kullanımı Onayla',
    redemptionWarningBody: 'Bu işlem aylık kullanım haklarınızdan birini düşecektir. Devam etmek istiyor musunuz?',
    dontShowAgain: "Bunu tekrar gösterme",
    confirmRedeem: 'Kullan',
    cancelRedeem: 'İptal',
    recommendedForYou: 'Sizin İçin Önerilenler',
    startExploringForRecommendations: 'Kişiselleştirilmiş öneriler almak için fırsatları keşfetmeye başlayın!',
    redeemNow: 'Şimdi Kullan',
    addToWallet: 'Cüzdana Ekle',
    addToWalletShort: 'Ekle',
    failedToClaimDeal: 'Fırsat cüzdana eklenemedi.',
    confirmAddToWallet: 'Cüzdana Ekle',
    // Limit Reached Modal
    limitReachedTitle: 'Limit Aşıldı',
    monthlyLimitReached: 'Aylık Limit Aşıldı',
    upgradePrompt: 'Bu ayki tüm kullanım haklarınızı doldurdunuz. Daha fazla harika fırsat için planınızı yükseltin!',
    upgradePlanButton: 'Planı Yükselt',
    maybeLater: 'Belki Daha Sonra',
    // Footer
    footerText: '© 2024 Tripzy. Tüm hakları saklıdır.',
  },
};